services:
  api:
    build: .
    container_name: fastapi-application
    environment:
      PORT: 80
    ports:
      - '80:80'
    deploy:
      resources:
        limits:
          cpus: '1.50'
          memory: 1024M

