services:
  backend:
    build: flask
    environment: 
      - FLASK_SERVER_PORT=9091
    ports:
      - 9091:9091
    depends_on:
      -  mongo  
  mongo:
    image: mongo
    ports:
      - 27017:27017
